# Makefile

all: global

solver:
	gcc solver.c solver.h -Wall -Wextra -o solver



clean:
	${RM} ${OBJ}   # remove object files
	${RM} ${DEP}   # remove dependency files
	${RM} solver   # remove main program

global:
	${RM} ${OBJ}   # remove object files
	${RM} ${DEP}   # remove dependency files
	${RM} solver   # remove main program
	gcc solver.c solver.h -Wall -Wextra -o solver




# END     





   
